### ISSUE TITLE
Admin portal error

### ISSUE THREAD

**Issue by vladanminic** [conwetlab/fiware-rss#1]
Dear conwet lab team,

after login on http://rss.lab.fiware.org:8080/fiware-rss I constantly got error 
Authorize RSS?
{"state": "xyz", "error": "mismatching_redirect_uri"} (HTTP 400)

Can you please re-check redirection URI of your admin RSS application?

Thank you!

Best regards,
Vladan

**Comment by vladanminic** [comment]
Can you please solve the problem with your admin panel or at least write something here?
Thank you!

**Comment by aitormagan** [comment]
Hi vladanminic,

We do not have access to the instance you are trying to use. Anyway, this instance is not intended for all the users of FIWARE Lab but only for WStore admins. If you want to use the RSS, please install it using the guides provided in this repo.

BR

**Comment by vladanminic** [comment]
Hi aitormagan,

in that case it would be nice to change official information on http://catalogue.fiware.org/enablers/revenue-settlement-and-sharing-system-rss-ri/instances

Any way, I tried to install RSS on my VM instance, I set up everything  according to http://fiware-rss.readthedocs.org/en/latest/installation-administration-guide.html but when I try to run app from Tomcat manager, I got HTTP Status 404 - /oauth2/authorize.

This part of official installation guide is also very confusing for me: The callback URL of the RSS. Must be something like http://[HOST]:[PORT]/fiware-rss/callback?client_name=FIWAREClient
This is the first time that I see in official instructions "Must be something like" and no other word to say about it. How should I know what your application expect as call back url? I tried different things, but in this case I don't think that this is the source of error above, otherwise I would get the same error as in my first post. Am I right?

The database is filled with tables, so I guess that communication with MySQL is OK and that this is not the source of the problem.

Do you have any idea why rss app doesn't work?

Thank you in advance!

Best regards,
Vladan

**Comment by fdelavega** [comment]
Hi,

The idm is using OAuth2 for authenticating users. In this regard, it requires to have a redirection URL where posting the access token, so the host and the port  of this URL should be the endpoint where you have delpoyed your instance of the RSS.

The "Must be something like"  sentence is witten that way because I cannot know in what host and port are you going to run your instance :-P

Please try to fix the OAuth2 configuration, and tell us if the problem persists.

Best regards,
Francisco
